[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
skip-string-normalization = true

[tool.isort]
profile = 'black'


[tool.coverage.run]
command_line = "-m pytest"
source = ["app"]

[tool.coverage.report]
show_missing = true

[tool.mypy]
mypy_path = "src"
